version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  etcd:
    image: bitnami/etcd
    ports:
      - "2379:2379"
    environment:
      ETCD_ROOT_PASSWORD: root
  cron:
    image: cron:v1
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
    depends_on:
      - redis
  account:
    image: account:v1
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
    depends_on:
      - etcd
      - redis
  price:
    image: price:v1
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
    depends_on:
      - etcd
      - redis
  gateway:
    image: gateway:v1
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
    depends_on:
      - etcd
      - redis
      - price
      - account
volumes:
  redis-data: