version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  etcd:
    image: bitnami/etcd
    ports:
      - "2379:2379"
    environment:
      ETCD_ROOT_PASSWORD: root
  cron:
    image: foliet/cron:v1
    depends_on:
      - redis
  account:
    image: foliet/account:v1
    network_mode: host
    depends_on:
      - etcd
      - redis
  price:
    image: foliet/price:v1
    network_mode: host
    depends_on:
      - etcd
      - redis
  gateway:
    image: foliet/gateway:v1
    network_mode: host
    depends_on:
      - etcd
      - redis
      - price
      - account
volumes:
  redis-data: