// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package accountclient

import (
	"context"

	"demo/service/account/rpc/pb/account"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest  = account.LoginRequest
	LoginResponse = account.LoginResponse

	Account interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
