// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	itemFieldNames          = builder.RawFieldNames(&Item{})
	itemRows                = strings.Join(itemFieldNames, ",")
	itemRowsExpectAutoSet   = strings.Join(stringx.Remove(itemFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	itemRowsWithPlaceHolder = strings.Join(stringx.Remove(itemFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	itemModel interface {
		Insert(ctx context.Context, data *Item) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Item, error)
		Update(ctx context.Context, data *Item) error
		Delete(ctx context.Context, id int64) error
	}

	defaultItemModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Item struct {
		Id       int64          `db:"id"`
		Url      sql.NullString `db:"url"`
		CreateAt sql.NullTime   `db:"create_at"`
	}
)

func newItemModel(conn sqlx.SqlConn) *defaultItemModel {
	return &defaultItemModel{
		conn:  conn,
		table: "`item`",
	}
}

func (m *defaultItemModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultItemModel) FindOne(ctx context.Context, id int64) (*Item, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itemRows, m.table)
	var resp Item
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItemModel) Insert(ctx context.Context, data *Item) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, itemRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Url)
	return ret, err
}

func (m *defaultItemModel) Update(ctx context.Context, data *Item) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, itemRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Url, data.Id)
	return err
}

func (m *defaultItemModel) tableName() string {
	return m.table
}
