// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userSubscribeFieldNames          = builder.RawFieldNames(&UserSubscribe{})
	userSubscribeRows                = strings.Join(userSubscribeFieldNames, ",")
	userSubscribeRowsExpectAutoSet   = strings.Join(stringx.Remove(userSubscribeFieldNames, "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userSubscribeRowsWithPlaceHolder = strings.Join(stringx.Remove(userSubscribeFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	userSubscribeModel interface {
		Insert(ctx context.Context, data *UserSubscribe) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserSubscribe, error)
		Update(ctx context.Context, data *UserSubscribe) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserSubscribeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserSubscribe struct {
		UserId int64 `db:"user_id"`
		ItemId int64 `db:"item_id"`
		Id     int64 `db:"id"`
	}
)

func newUserSubscribeModel(conn sqlx.SqlConn) *defaultUserSubscribeModel {
	return &defaultUserSubscribeModel{
		conn:  conn,
		table: "`user_subscribe`",
	}
}

func (m *defaultUserSubscribeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserSubscribeModel) FindOne(ctx context.Context, id int64) (*UserSubscribe, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userSubscribeRows, m.table)
	var resp UserSubscribe
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSubscribeModel) Insert(ctx context.Context, data *UserSubscribe) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userSubscribeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ItemId, data.Id)
	return ret, err
}

func (m *defaultUserSubscribeModel) Update(ctx context.Context, data *UserSubscribe) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userSubscribeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ItemId, data.Id)
	return err
}

func (m *defaultUserSubscribeModel) tableName() string {
	return m.table
}
