// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	account "demo/service/gateway/api/internal/handler/account"
	price "demo/service/gateway/api/internal/handler/price"
	"demo/service/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: account.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: account.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/account"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add_subscribe",
				Handler: price.AddSubscribeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/query_subscribe",
				Handler: price.QuerySubscribeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list_subscribe",
				Handler: price.ListSubscribeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/price"),
	)
}
