// Code generated by goctl. DO NOT EDIT!

package sql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	subscribeFieldNames          = builder.RawFieldNames(&Subscribe{})
	subscribeRows                = strings.Join(subscribeFieldNames, ",")
	subscribeRowsExpectAutoSet   = strings.Join(stringx.Remove(subscribeFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	subscribeRowsWithPlaceHolder = strings.Join(stringx.Remove(subscribeFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	subscribeModel interface {
		Insert(ctx context.Context, data *Subscribe) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Subscribe, error)
		Update(ctx context.Context, data *Subscribe) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSubscribeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Subscribe struct {
		Id     int64 `db:"id"`
		UserId int64 `db:"user_id"`
		ItemId int64 `db:"item_id"`
		ShopId int64 `db:"shop_id"`
	}
)

func newSubscribeModel(conn sqlx.SqlConn) *defaultSubscribeModel {
	return &defaultSubscribeModel{
		conn:  conn,
		table: "`subscribe`",
	}
}

func (m *defaultSubscribeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSubscribeModel) FindOne(ctx context.Context, id int64) (*Subscribe, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", subscribeRows, m.table)
	var resp Subscribe
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubscribeModel) Insert(ctx context.Context, data *Subscribe) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, subscribeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ItemId, data.ShopId)
	return ret, err
}

func (m *defaultSubscribeModel) Update(ctx context.Context, data *Subscribe) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, subscribeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ItemId, data.ShopId, data.Id)
	return err
}

func (m *defaultSubscribeModel) tableName() string {
	return m.table
}
