// Code generated by goctl. DO NOT EDIT.
package types

type CodeResponse struct {
	Code int64  `json:"code,default=0"`
	Msg  string `json:"msg,default=''"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	CodeResponse
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Code     string `json:"code"`
}

type RegisterResponse struct {
	CodeResponse
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type Subscribe struct {
	ItemId int64 `json:"itemId"`
	ShopId int64 `json:"shopId"`
}

type ItemInfo struct {
	ItemId   int64   `json:"itemId"`
	CreateAt int64   `json:"createAt"`
	Price    float64 `json:"price"`
}

type AddSubscribeRequest struct {
	Url string `json:"url"`
}

type QuerySubscribeRequest struct {
	Subscribe
}

type QuerySubscribeResponse struct {
	CodeResponse
	ItemInfos []*ItemInfo `json:"itemInfos"`
}

type ListSubscribeResponse struct {
	Subscribes []*Subscribe `json:"subscribes"`
}
