// Code generated by goctl. DO NOT EDIT.
package types

type ResponseStatus struct {
	Code int64  `json:"code,default=0"`
	Msg  string `json:"msg,default=''"`
}

type Empty struct {
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	ResponseStatus
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Code     string `json:"code"`
}

type RegisterResponse struct {
	ResponseStatus
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type SubscribeRequest struct {
	ItemId int64 `json:"itemId"`
	ShopId int64 `json:"shopId"`
}

type ItemInfo struct {
	ItemId   int64   `json:"itemId"`
	CreateAt int64   `json:"createAt"`
	Price    float64 `json:"price"`
}

type ItemInfoResponse struct {
	ResponseStatus
	ItemInfos []*ItemInfo `json:"itemInfos"`
}
