// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Code     string `json:"code"`
}

type RegisterResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type Item struct {
	ItemId int64 `json:"itemId"`
	ShopId int64 `json:"shopId,optional"`
}

type ItemInfo struct {
	ItemId   int64   `json:"itemId"`
	CreateAt int64   `json:"createAt"`
	Price    float64 `json:"price"`
}

type ItemInfos struct {
	ItemInfos []*ItemInfo `json:"itemInfos"`
}
