// Code generated by goctl. DO NOT EDIT!
// Source: price.proto

package server

import (
	"context"

	"demo/service/price/rpc/internal/logic"
	"demo/service/price/rpc/internal/svc"
	"demo/service/price/rpc/pb"
)

type PriceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPriceServer
}

func NewPriceServer(svcCtx *svc.ServiceContext) *PriceServer {
	return &PriceServer{
		svcCtx: svcCtx,
	}
}

func (s *PriceServer) AddSubscribe(ctx context.Context, in *pb.AddSubscribeRequest) (*pb.Empty, error) {
	l := logic.NewAddSubscribeLogic(ctx, s.svcCtx)
	return l.AddSubscribe(in)
}

func (s *PriceServer) ListSubscribe(ctx context.Context, in *pb.ListSubscribeRequest) (*pb.ListSubscribeResponse, error) {
	l := logic.NewListSubscribeLogic(ctx, s.svcCtx)
	return l.ListSubscribe(in)
}

func (s *PriceServer) QuerySubscribe(ctx context.Context, in *pb.QuerySubscribeRequest) (*pb.QuerySubscribeResponse, error) {
	l := logic.NewQuerySubscribeLogic(ctx, s.svcCtx)
	return l.QuerySubscribe(in)
}
