// Code generated by goctl. DO NOT EDIT!
// Source: price.proto

package server

import (
	"context"

	"demo/service/price/rpc/internal/logic"
	"demo/service/price/rpc/internal/svc"
	"demo/service/price/rpc/pb"
)

type PriceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPriceServer
}

func NewPriceServer(svcCtx *svc.ServiceContext) *PriceServer {
	return &PriceServer{
		svcCtx: svcCtx,
	}
}

func (s *PriceServer) Subscribe(ctx context.Context, in *pb.SubscribeRequest) (*pb.Empty, error) {
	l := logic.NewSubscribeLogic(ctx, s.svcCtx)
	return l.Subscribe(in)
}

func (s *PriceServer) ItemInfo(ctx context.Context, in *pb.UserId) (*pb.ItemInfos, error) {
	l := logic.NewItemInfoLogic(ctx, s.svcCtx)
	return l.ItemInfo(in)
}
