// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package server

import (
	"context"
	"demo/service/account/rpc/pb"

	"demo/service/account/rpc/internal/logic"
	"demo/service/account/rpc/internal/svc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
