// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package server

import (
	"context"

	"demo/service/account/rpc/internal/logic"
	"demo/service/account/rpc/internal/svc"
	"demo/service/account/rpc/pb"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.UserId, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AccountServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.UserId, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
